### ISSUE TITLE
图片都看不到，无法扫二维码

### ISSUE THREAD

**Issue by ssxsite** [lgwebdream/FE-Interview#1030]

**Comment by Genzhen** [comment]
### 原因

github 图片访问不到，有可能是下面原因

- dns污染
- host设置错误
- 官方更新了dns，但是dns缓存没有被更新，导致解析错误

### 解决方式

主要思路就是使用本地hosts文件对网站进行域名解析，一般的DNS问题都可以通过修改hosts文件来解决，github的CDN域名被污染问题也不例外，同样可以通过修改hosts文件解决，将域名解析直接指向IP地址来绕过DNS的解析，以此解决污染问题。

#### 1.找到url

打开github任意未显示图片的网页，使用元素选择器（Ctrl+Shift+C）放在显示不了的图片上，或者在无法显示的图片上右键-检查元素，定位到该图片的标签，那么你得到了它的URL，叫做src属性。

把图片的网址复制出来

https://camo.githubusercontent.com/e1d0c2ddfd732a2a28f2ccbf34c0d45f87d3e8c14863f33f63a4ef699bfd7733/687474703a2f2f696d672d7374617469632e796964656e6778756574616e672e636f6d2f77786170702f69737375652d696d672f77782d717565732d71722e706e67

#### 2.获取ip地址

得到上述网址以后打开[IPAddress.com](https://www.ipaddress.com/)这个网站，在搜索框输入它的域名，就是`https://`到com那一部分，俗称二级域名：`camo.githubusercontent.com`

就会得到ip地址。

#### 3.修改hosts文件

- window系统路径：`C:\Windows\System32\drivers\etc\hosts`

在末尾添加

```js
199.232.96.133  camo.githubusercontent.com
```

然后保存文件就ok了。

- mac系统 可以使用switchhosts软件 修改
- mac 系统hosts文件路径  `/etc/hosts`，可以在终端中，`vi /etx/hosts`

### 微信小程序中搜索【前端面试星球】，可直接进行刷题

> 二维码加载失败可点击 [小程序二维码](http://img-static.yidengxuetang.com/wxapp/issue-img/wx-ques-qr.png)
